config/routes.rb
Supost::Application.routes.draw do
  root :to => 'site#index'

  # Admin
  namespace :admin do
    root :to => 'posts#index'

    resources :events, :only => [:index]

    resources :payments, :only => [:index]

    resources :spammers, :only => [:index, :create, :destroy] do
      member do
        get :posts
      end
    end

    resources :scammers, :only => [:index, :create, :destroy] do
      member do
        get :messages
      end
      collection do
        get :find
      end
    end

    resources :messages, :only => [:index] do
      member do
        get  :similar
        get  :report
        post :report
      end
    end

    get 'profile'  => 'users#profile',  :as => :profile
    put 'profile'  => 'users#profile',  :as => :profile

    get 'password' => 'users#password', :as => :password
    put 'password' => 'users#password', :as => :password

    resources :users do
      member do
        post :reset
      end
    end

    resources :posts do
      member do
        get  :readonly
        post :publish
        post :release
        post :notify
        get  :similar
        get  :report
        post :report
      end
      collection do
        get :job
      end
      resources :messages, :only => :index
    end

    get  'login'  => 'sessions#new',     :as => :login
    post 'login'  => 'sessions#create',  :as => :login
    get  'logout' => 'sessions#destroy', :as => :logout
  end

  mount DelayedJobWeb => '/delayed_job'

  # Stripe
  post '/webhook'         => 'stripe#webhook'
  post '/charge/:post_id' => 'stripe#charge', :as => :charge

  # Site
  get '/about'        => 'site#about',   :as => :about
  get '/contact'      => 'site#contact', :as => :contact
  get '/privacy'      => 'site#privacy', :as => :privacy
  get '/terms'        => 'site#terms',   :as => :terms
  get '/help'         => 'site#help',    :as => :help
  get '/safety'       => 'site#safety',  :as => :safety
  get '/status'       => 'site#state',   :as => :status
  get '/robots.txt'   => 'site#robots',  :as => nil

  # Legacy
  # TODO: Remove this on 2016-10-01
  get '/site(/index)' => 'site#index',   :as => nil
  get '/site/about'   => 'site#about',   :as => nil
  get '/site/contact' => 'site#contact', :as => nil
  get '/site/privacy' => 'site#privacy', :as => nil
  get '/site/terms'   => 'site#terms',   :as => nil
  get '/site/help'    => 'site#help',    :as => nil

  # Add
  get  '/add'                          => 'add#index',   :as => :new_post
  get  '/add/cat/:cat(/sub/:sub)'      => 'add#index',   :as => :add_post
  post '/add/cat/:cat(/sub/:sub)'      => 'add#index',   :as => :add_post
  get  '/add/preview/:id'              => 'add#preview', :as => :preview_post
  post '/add/confirm/:id'              => 'add#confirm', :as => :confirm_post
  get  '/add/success'                  => 'add#success', :as => :success

  # Legacy
  # TODO: Remove this on 2016-10-01
  get  '/add/index(/:cat)' => 'add#index', :as => nil
  post '/add/index/:cat'   => 'add#index', :as => nil

  # Post
  get  '/post/index/:id'             => 'post#index',   :as => :post
  post '/post/index/:id'             => 'post#index',   :as => :post
  get  '/post/publish/:access_token' => 'post#publish', :as => :publish_post
  get  '/post/delete/:access_token'  => 'post#delete',  :as => :delete_post

  # Legacy
  # TODO: Remove this on 2016-10-01
  get '/add/publish/:id/:security_id' => 'post#legacy_publish', :as => nil
  get '/add/publish/:id'              => 'post#legacy_publish', :as => nil
  get '/add/delete/:id/:security_id'  => 'post#legacy_delete',  :as => nil
  get '/add/delete/:id'               => 'post#legacy_delete',  :as => nil

  # Search
  get '/search/cat/:cat'     => 'search#index', :as => :search_by_cat
  get '/search/sub/:sub'     => 'search#index', :as => :search_by_sub
  get '/search'              => 'search#index', :as => :search

  # Legacy
  # TODO: Remove this on 2016-10-01
  get '/search/index(/:cat)' => 'search#index', :as => nil

  # Job
  get '/job'             => 'job#index',       :as => :job
  get '/subscriber'      => 'job#subscriber',  :as => :subscriber
  get '/unsubscribe'     => 'job#unsubscribe', :as => :unsubscribe
  get '/success'         => 'job#success',     :as => nil

  # Legacy
  # TODO: Remove this on 2016-10-01
  get '/job/index'       => 'job#index',       :as => nil
  get '/job/subscriber'  => 'job#subscriber',  :as => nil
  get '/job/unsubscribe' => 'job#unsubscribe', :as => nil

  # Redirect unknown to to home page
  # match '*path' => redirect('/')
end

app/models/notifier.rb
class Notifier < ActionMailer::Base
  include ActionView::Helpers::NumberHelper

  NO_REPLY      = 'SUpost <response@mg.supost.com>'
  BCC_EMAIL     = 'aileen@suposts.com'
  BCC_PAY       = %w(bcc-pay@supost.com supost.emailbot@gmail.com)
  DEV_EMAIL     = 'nhphong1406@gmail.com'
  STAGING_EMAIL = 'gwientjes@gmail.com'

  helper_method :price_tag

  default :content_transfer_encoding => '7bit',
          :content_type              => 'text/plain',
          :charset                   => 'UTF-8',
          :from                      => NO_REPLY

  def complete_purchase_buyer(payment)
    find_payment_and_post(payment)

    options = {
      :to       => filter_email(@payment.buyer),
      :reply_to => @payment.seller,
      :subject  => "SUpost Purchase Success - Contact: #{@payment.seller}: #{@post.name}"
    }
    options.merge!(:bcc => BCC_PAY) if Rails.env.production?

    mail(options)
  end

  def complete_purchase_seller(payment)
    find_payment_and_post(payment)

    options = {
      :to       => filter_email(@payment.seller),
      :reply_to => @payment.buyer,
      :subject  => "SUpost Purchase Success - Contact: #{@payment.buyer}: #{@post.name}"
    }
    options.merge!(:bcc => BCC_PAY) if Rails.env.production?

    mail(options)
  end

  def complete_reservation_buyer(payment)
    find_payment_and_post(payment)

    options = {
      :to       => filter_email(@payment.buyer),
      :reply_to => @payment.seller,
      :subject  => "SUpost Reservation Success - Contact: #{@payment.seller}: #{@post.name}"
    }
    options.merge!(:bcc => BCC_PAY) if Rails.env.production?

    mail(options)
  end

  def complete_reservation_seller(payment)
    find_payment_and_post(payment)

    options = {
      :to       => filter_email(@payment.seller),
      :reply_to => @payment.buyer,
      :subject  => "SUpost Reservation Success - Contact: #{@payment.buyer}: #{@post.name}"
    }
    options.merge!(:bcc => BCC_PAY) if Rails.env.production?

    mail(options)
  end

  def activate(post)
    @post = post.is_a?(Post) ? post : Post.find(post)

    options = {
      :to      => filter_email(@post.email),
      :subject => "SUpost - Publish your post! #{@post.name}"
    }

    mail(options)
  end

  def response(message)
    @message = message.is_a?(Message) ? message : Message.find(message)
    @post    = @message.post

    options = {
      :from    => @message.email,
      :sender  => NO_REPLY,
      :to      => filter_email(@post.email),
      :subject => "SUpost - #{@message.email} response: #{@post.name}"
    }
    options.merge!(:bcc => BCC_EMAIL) if Rails.env.production?

    mail(options)
  end

  private

  def filter_email(email)
    if Rails.env.production?
      email
    elsif Rails.env.staging?
      [DEV_EMAIL, STAGING_EMAIL]
    else
      DEV_EMAIL
    end
  end

  def price_tag(price)
    number_to_currency(price, :precision => price.is_a?(Integer) ? 0 : 2)
  end

  def find_payment_and_post(payment)
    @payment = payment.is_a?(Payment) ? payment : Payment.find(payment)
    @post    = @payment.post
  end
end

app/views/notifier/_post_details.text.erb
<%- type = @payment.display_checkout_type -%>
More information about SUpost Pay can be found at http://pay.supost.com.

If you have any questions or concerns about your <%= type %>, you may submit a question at http://pay.supost.com/questions.html

<%- if receiver == :buyer -%>
Details of your <%= type.titlecase %>:
<%- else -%>
Details of the <%= type.titlecase %>:
<%- end -%>
Post: <%= @post.name %>
<%= post_url(@post) %>
Post Price: <%= price_tag @post.rounded_price %>
Date Posted: <%= @post.display_posted_at %>
Email of Seller: <%= @post.email %>
Email of Buyer: <%= @payment.buyer %>

Description:
<%= @post.body %>

app/views/notifier/_purchase_details.text.erb
<%- type = @payment.display_checkout_type -%>
Post: <%= @post.name %>
<%= post_url(@post) %>
Post Price: <%= price_tag @post.rounded_price %>

Email of Seller: <%= @payment.seller %>
Email of Buyer: <%= @payment.buyer %>

<%- if @payment.is_purchase? -%>
Service Fee: <%= price_tag @payment.rounded_fee %>
Amount Paid: <%= price_tag @payment.rounded_amount %>
<%- elsif receiver == :buyer -%>
Reservation Cost Paid: <%= price_tag @payment.rounded_amount %>
<%- end -%>
Date of <%= type.titlecase %>: <%= @payment.display_date %>

app/views/notifier/activate.text.erb
Publish your post by pressing:
<%= publish_post_url(@post.access_token) %>

<%= @post.name.html_safe %>
Posted on: <%= @post.display_posted_at %> -- Stanford University

Do not send electronic payments to sellers: http://safety.supost.com

app/views/notifier/complete_purchase_buyer.text.erb
Your purchase on SUpost succeeded!

<%= render 'purchase_details', :receiver => :buyer %>

With the seller's email listed above, contact the seller directly in order to receive your item or service. Since your payment was successful, no other charges should be required for your post purchased above. The seller will receive payment after 5 business days through a PayPal money transfer.

By making a purchase, the post is deleted from the SUpost listings. You and the seller have the responsibility to complete the transaction.

The seller may decline your electronic purchase. In such cases, you will be refunded. To receive your refund, you must inform us within 3 business days of purchase at http://pay.supost.com/questions.html

<%= render 'post_details', :receiver => :buyer %>

app/views/notifier/complete_purchase_seller.text.erb
You received a payment for your post on SUpost!

Please email the buyer to complete the purchase: <%= @payment.buyer %>.
You will receive the payout for your post after 5 business days. You will receive your payout by a PayPal money transfer sent to the email you used to make the post: <%= @post.email %>. A service fee is required to receive your payout. See http://pay.supost.com to view more information about receiving your payout through PayPal and the service fee. If you do not have a PayPal.com account, please make one with <%= @post.email %> at: https://www.paypal.com/signup

If you need to decline the purchase, please notify the buyer and SUpost of your decision to not complete the purchase at: http://pay.supost.com/questions.html

<%= render 'purchase_details', :receiver => :seller %>

When the buyer made the payment for your post, your post was deleted from the SUpost listings. You and the buyer have the responsibility to complete the transaction.

<%= render 'post_details', :receiver => :seller %>

app/views/notifier/complete_reservation_buyer.text.erb
Your reservation on SUpost succeeded!

<%= render 'purchase_details', :receiver => :buyer %>

With the seller's email listed above, contact the seller directly. This notification is a confirmation of your reservation for the post. The money spent for this reservation will not go to the seller. The seller will require you to pay the post price listed above in order for you to receive the item.

By making a reservation, the post is deleted from the SUpost listings. You and the seller have the responsibility to complete the purchase.

The seller may decline your reservation. In such cases, you will be refunded. To receive your refund, you must inform us within 3 business days at http://pay.supost.com/questions.html

<%= render 'post_details', :receiver => :buyer %>

app/views/notifier/complete_reservation_seller.text.erb
You received a reservation for your post on SUpost!

Please email the buyer to complete the purchase: <%= @payment.buyer %>.

If you need to decline the reservation, please notify the buyer and SUpost of your decision to not complete the purchase at: http://pay.supost.com/questions.html

<%= render 'purchase_details', :receiver => :seller %>

When the buyer made the reservation for your post, your post was deleted from the SUpost listings. You and the buyer have the responsibility to complete the transaction.

<%= render 'post_details', :receiver => :seller %>

app/views/notifier/response.text.erb
<%= @message.display_message.html_safe %>

From: <%= @message.email %>



<%= @post.name.html_safe %> - Posted: <%= @post.display_posted_at %>

To delete your post, use this link and click 'Delete your post.'
<%= publish_post_url(@post.access_token) %>

Do not send electronic payments to sellers: http://safety.supost.com

<%= post_url(@post.id) %>