config/routes.rb
Supost::Application.routes.draw do
  root :to => 'site#index'

  # Admin
  namespace :admin do
    root :to => 'posts#index'

    resources :events, :only => [:index]

    resources :payments, :only => [:index]

    resources :spammers, :only => [:index, :create, :destroy] do
      member do
        get :posts
      end
    end

    resources :scammers, :only => [:index, :create, :destroy] do
      member do
        get :messages
      end
      collection do
        get :find
      end
    end

    resources :messages, :only => [:index] do
      member do
        get  :similar
        get  :report
        post :report
      end
    end

    get 'profile'  => 'users#profile',  :as => :profile
    put 'profile'  => 'users#profile',  :as => :profile

    get 'password' => 'users#password', :as => :password
    put 'password' => 'users#password', :as => :password

    resources :users do
      member do
        post :reset
      end
    end

    resources :posts do
      member do
        get  :readonly
        post :publish
        post :release
        post :notify
        get  :similar
        get  :report
        post :report
      end
      collection do
        get :job
      end
      resources :messages, :only => :index
    end

    get  'login'  => 'sessions#new',     :as => :login
    post 'login'  => 'sessions#create',  :as => :login
    get  'logout' => 'sessions#destroy', :as => :logout
  end

  mount DelayedJobWeb => '/delayed_job'

  # Stripe
  post '/webhook'         => 'stripe#webhook'
  post '/charge/:post_id' => 'stripe#charge', :as => :charge

  # Site
  get '/about'        => 'site#about',   :as => :about
  get '/contact'      => 'site#contact', :as => :contact
  get '/privacy'      => 'site#privacy', :as => :privacy
  get '/terms'        => 'site#terms',   :as => :terms
  get '/help'         => 'site#help',    :as => :help
  get '/safety'       => 'site#safety',  :as => :safety
  get '/status'       => 'site#state',   :as => :status
  get '/robots.txt'   => 'site#robots',  :as => nil

  # Legacy
  # TODO: Remove this on 2016-10-01
  get '/site(/index)' => 'site#index',   :as => nil
  get '/site/about'   => 'site#about',   :as => nil
  get '/site/contact' => 'site#contact', :as => nil
  get '/site/privacy' => 'site#privacy', :as => nil
  get '/site/terms'   => 'site#terms',   :as => nil
  get '/site/help'    => 'site#help',    :as => nil

  # Add
  get  '/add'                          => 'add#index',   :as => :new_post
  get  '/add/cat/:cat(/sub/:sub)'      => 'add#index',   :as => :add_post
  post '/add/cat/:cat(/sub/:sub)'      => 'add#index',   :as => :add_post
  get  '/add/preview/:id'              => 'add#preview', :as => :preview_post
  post '/add/confirm/:id'              => 'add#confirm', :as => :confirm_post
  get  '/add/success'                  => 'add#success', :as => :success

  # Legacy
  # TODO: Remove this on 2016-10-01
  get  '/add/index(/:cat)' => 'add#index', :as => nil
  post '/add/index/:cat'   => 'add#index', :as => nil

  # Post
  get  '/post/index/:id'             => 'post#index',   :as => :post
  post '/post/index/:id'             => 'post#index',   :as => :post
  get  '/post/publish/:access_token' => 'post#publish', :as => :publish_post
  get  '/post/delete/:access_token'  => 'post#delete',  :as => :delete_post

  # Legacy
  # TODO: Remove this on 2016-10-01
  get '/add/publish/:id/:security_id' => 'post#legacy_publish', :as => nil
  get '/add/publish/:id'              => 'post#legacy_publish', :as => nil
  get '/add/delete/:id/:security_id'  => 'post#legacy_delete',  :as => nil
  get '/add/delete/:id'               => 'post#legacy_delete',  :as => nil

  # Search
  get '/search/cat/:cat'     => 'search#index', :as => :search_by_cat
  get '/search/sub/:sub'     => 'search#index', :as => :search_by_sub
  get '/search'              => 'search#index', :as => :search

  # Legacy
  # TODO: Remove this on 2016-10-01
  get '/search/index(/:cat)' => 'search#index', :as => nil

  # Job
  get '/job'             => 'job#index',       :as => :job
  get '/subscriber'      => 'job#subscriber',  :as => :subscriber
  get '/unsubscribe'     => 'job#unsubscribe', :as => :unsubscribe
  get '/success'         => 'job#success',     :as => nil

  # Legacy
  # TODO: Remove this on 2016-10-01
  get '/job/index'       => 'job#index',       :as => nil
  get '/job/subscriber'  => 'job#subscriber',  :as => nil
  get '/job/unsubscribe' => 'job#unsubscribe', :as => nil

  # Redirect unknown to to home page
  # match '*path' => redirect('/')
end

app/controllers/add_controller.rb
class AddController < ApplicationController
  before_filter :find_post, :only => [:preview, :confirm]

  def index
    if request.post?
      save_post
    else
      new_post
    end
  end

  def preview
    @post.enable_purchases = true
    @category = @post.category
    @subcategory = @post.subcategory
  end

  def confirm
    @post.update_attributes(:enable_purchases => params[:post].try(:[], :enable_purchases))
    unless Spammer.spam_email?(@post.email)
      store_email_in_cookies(@post)
      @post.send_activation_mail!
    end
    @post.mark_as_confirmed!
    redirect_to success_url
  end

  def success
  end

  private

  def find_post
    @post = Post.find(params[:id])
    redirect_to post_url(@post.id) and return if @post.ready?
  end

  def new_post
    if params[:cat].present?
      @category = Category.find_by_id(params[:cat])

      redirect_to add_post_url and return if @category.blank? || @category.inactive?
      redirect_to buy_job_post_link and return if @category.off_campus_jobs?

      if params[:sub].present?
        @subcategory = @category.subcategories.find_by_id(params[:sub])

        redirect_to add_post_url(@category.id) and return if @subcategory.blank?
      else
        @subcategories = @category.subcategories.all(:order => 'name')
      end

      @post = Post.new(
        :category    => @category,
        :subcategory => @subcategory,
        :email       => email_from_cookies
      )
    end
  end

  def save_post
    @category    = Category.find(params[:cat])
    @subcategory = Subcategory.find(params[:sub])

    @post = Post.new_with_default_values(post_params)
    @post.ip          = request_ip
    @post.category    = @category
    @post.subcategory = @subcategory

    if @post.save_with_photos(raw_photos)
      store_email_in_cookies(@post)
      redirect_to preview_post_url(@post.id) and return
    end
  end

  def post_params
    params[:post].slice(:name, :price, :body, :email)
  end

  def raw_photos
    params[:post].slice(:photo1, :photo2, :photo3, :photo4)
  end

  def buy_job_post_link
    "http://jobs.suposts.com"
  end

  def email_from_cookies
    cookies.signed[:_supost_poster]
  end

  def store_email_in_cookies(post)
    cookies.signed[:_supost_poster] = { :value => post.email, :expires => 3.months.from_now }
  end
end

app/views/add/_add_form.erb
<%= form_for @post, :as => :post, :url => add_post_path(@category.id, :sub => @subcategory.id), :html => { :multipart => true } do |f| %>
  <div class="add_post_form">
    <%= error_messages_for :post %>

    <div class="form_row">
      <span class="form_label"><%= f.label :name, 'Post Title:' %></span>
      <span class="form_input">
        <%= f.text_field :name, :class => "input_text_field", :maxlength => 70 %>
      </span>
    </div>

    <% if @post.price_required? %>
      <div class="form_row">
        <span class="form_label"><%= f.label :price, 'Price:' %></span>
        <span class="form_input">
          <%= f.number_field :price, :min => 0, :max => 1_000_000, :step => 0.01, :class => 'input_text_field', :maxlength => 10 %>
        </span>
      </div>
    <% end %>

    <div class="form_row">
      <span class="form_label"><%= f.label :body, 'Post Description:' %></span>
      <span class="form_input">
        <%= f.text_area :body, :class => 'input_textarea_field' %>
      </span>
    </div>

    <div class="form_row">
      <span class="form_label"><%= f.label :email, 'Your Stanford Email:' %></span>
      <span class="form_input">
        <%= f.text_field :email, :class => "input_text_field", :maxlength => 70 %>

        <div class="no-spam milder email-notes">
          @stanford.edu, @alumni.stanford.edu, @stanfordalumni.org<br />
          We need your email to send you the self-publishing link. This email will not be visible on the website.
        </div>
      </span>
    </div>

    <div class="form_row">
      <span class="form_label form_photo_label"><%= f.label :photo1, 'Photos:' %></span>
      <div class="form_input">
        <div class="form_photo_field first">
          <%= f.file_field :photo1 %>
          <span class="photo_optional">optional</span>
        </div>
        <div class="form_photo_field"><%= f.file_field :photo2 %></div>
        <div class="form_photo_field"><%= f.file_field :photo3 %></div>
        <div class="form_photo_field"><%= f.file_field :photo4 %></div>
      </div>
    </div>
  </div>

  <div class="submit_row">
    <%= f.submit 'Preview', :disable_with => 'Saving...', :class => 'submit' %>
  </div>

  <%= render :partial => '/post/no_housing_spam' %>
<% end %>

app/views/add/_select_category.erb
<div class="addFormCategory">
  <div class="addFormHeader">What type of post is this? </div>
  <ul>
    <li><%= link_to 'for sale / wanted', add_post_path(Category::FOR_SALE) %></li>
    <li><%= link_to 'personals', add_post_path(Category::PERSONALS) %></li>
    <li><%= link_to 'housing (offering)', add_post_path(Category::HOUSING_OFFERING) %></li>
    <li><%= link_to 'housing (need)', add_post_path(Category::HOUSING_NEED) %></li>
    <li><%= link_to 'community', add_post_path(Category::COMMUNITY) %></li>
    <li><%= link_to 'service offered', add_post_path(Category::SERVICES) %></li>
    <li><%= link_to 'campus job', add_post_path(Category::CAMPUS_JOBS) %></li>
    <li><%= link_to 'job off-campus', buy_job_post_link %></li>
    <!--
    <li><%= link_to 'resume', add_post_path(Category::RESUMES, :sub => Subcategory::RESUMES_GENERAL) %></li>
    -->
  </ul>
</div>

app/views/add/_select_subcategory.erb
<div class="addFormCategory">
  <div class="addFormHeader">Please choose a category: </div>
  <% @subcategories.each do |subcategory| %>
    <ul>
      <li>
        <%= link_to subcategory.name, add_post_path(subcategory.category_id, :sub => subcategory.id) %>
      </li>
    </ul>
  <% end %>
</div>

app/views/add/index.html.erb
<div class="addFormContent">
  <div class="addFormBanner">
    <span class="collegeAddForm">(Stanford)</span>
  </div>

  <% if @category.blank? %>
    <%= render :partial => 'select_category' %>
  <% elsif @subcategory.blank? %>
    <%= render :partial => 'select_subcategory' %>
  <% else %>
    <%= render :partial => 'add_form' %>
  <% end %>
</div>

app/views/add/preview.html.erb
<%= render :partial => '/post/post' %>

<div class="continue-step">
  <%= form_for @post, :url => confirm_post_path(@post.id), :html => { :method => :post } do |f| %>
    <% if @post.purchasable? %>
      <div class="field_row">
        <%= f.check_box :enable_purchases %>
        <% label_tag :post_enable_purchases do %>
          Enable
          <%= link_to 'electronic purchases', '//pay.supost.com', :target => '_blank' %>
          of my post.
          I agree to a payout via PayPal to my email, <%= @post.email %>,
          after 5 business days and a 25% service fee.
        <% end %>
      </div>
    <% end %>

    <div class="submit_row">
      <%= submit_tag 'Continue', :disable_with => 'Saving...' %>
    </div>
  <% end %>
</div>

app/views/add/success.html.erb
<div id="posting-confirmation" class="confirm-msg">
  <h2>You will receive an email shortly,</h2> containing a link that will allow you to

  <div class="message">
    publish your post.
    <div>
      <span class="important" style="font-weight:bold">PLEASE KEEP THIS EMAIL</span>
      -- you will need it to delete your post when you are done.
      <br /><br />
      <div>
        Your email provider might misfile this mail as spam.
        <span style="font-weight:bold">Please check your spam folders.</span>
        <br /><br />
        If you do not receive this email, please consult our <%= link_to 'help pages', help_path %>.
      </div>
    </div>
  </div>
</div>

<div style="margin-top:20px;">
  Thank you for using SUpost!
  <ul>
    <li><%= link_to 'Start another post.', new_post_path %></li>
    <li><%= link_to 'Return to SUpost.', root_path %></li>
  </ul>
</div>