config/routes.rb
Supost::Application.routes.draw do
  root :to => 'site#index'

  # Admin
  namespace :admin do
    root :to => 'posts#index'

    resources :events, :only => [:index]

    resources :payments, :only => [:index]

    resources :spammers, :only => [:index, :create, :destroy] do
      member do
        get :posts
      end
    end

    resources :scammers, :only => [:index, :create, :destroy] do
      member do
        get :messages
      end
      collection do
        get :find
      end
    end

    resources :messages, :only => [:index] do
      member do
        get  :similar
        get  :report
        post :report
      end
    end

    get 'profile'  => 'users#profile',  :as => :profile
    put 'profile'  => 'users#profile',  :as => :profile

    get 'password' => 'users#password', :as => :password
    put 'password' => 'users#password', :as => :password

    resources :users do
      member do
        post :reset
      end
    end

    resources :posts do
      member do
        get  :readonly
        post :publish
        post :release
        post :notify
        get  :similar
        get  :report
        post :report
      end
      collection do
        get :job
      end
      resources :messages, :only => :index
    end

    get  'login'  => 'sessions#new',     :as => :login
    post 'login'  => 'sessions#create',  :as => :login
    get  'logout' => 'sessions#destroy', :as => :logout
  end

  mount DelayedJobWeb => '/delayed_job'

  # Stripe
  post '/webhook'         => 'stripe#webhook'
  post '/charge/:post_id' => 'stripe#charge', :as => :charge

  # Site
  get '/about'        => 'site#about',   :as => :about
  get '/contact'      => 'site#contact', :as => :contact
  get '/privacy'      => 'site#privacy', :as => :privacy
  get '/terms'        => 'site#terms',   :as => :terms
  get '/help'         => 'site#help',    :as => :help
  get '/safety'       => 'site#safety',  :as => :safety
  get '/status'       => 'site#state',   :as => :status
  get '/robots.txt'   => 'site#robots',  :as => nil

  # Legacy
  # TODO: Remove this on 2016-10-01
  get '/site(/index)' => 'site#index',   :as => nil
  get '/site/about'   => 'site#about',   :as => nil
  get '/site/contact' => 'site#contact', :as => nil
  get '/site/privacy' => 'site#privacy', :as => nil
  get '/site/terms'   => 'site#terms',   :as => nil
  get '/site/help'    => 'site#help',    :as => nil

  # Add
  get  '/add'                          => 'add#index',   :as => :new_post
  get  '/add/cat/:cat(/sub/:sub)'      => 'add#index',   :as => :add_post
  post '/add/cat/:cat(/sub/:sub)'      => 'add#index',   :as => :add_post
  get  '/add/preview/:id'              => 'add#preview', :as => :preview_post
  post '/add/confirm/:id'              => 'add#confirm', :as => :confirm_post
  get  '/add/success'                  => 'add#success', :as => :success

  # Legacy
  # TODO: Remove this on 2016-10-01
  get  '/add/index(/:cat)' => 'add#index', :as => nil
  post '/add/index/:cat'   => 'add#index', :as => nil

  # Post
  get  '/post/index/:id'             => 'post#index',   :as => :post
  post '/post/index/:id'             => 'post#index',   :as => :post
  get  '/post/publish/:access_token' => 'post#publish', :as => :publish_post
  get  '/post/delete/:access_token'  => 'post#delete',  :as => :delete_post

  # Legacy
  # TODO: Remove this on 2016-10-01
  get '/add/publish/:id/:security_id' => 'post#legacy_publish', :as => nil
  get '/add/publish/:id'              => 'post#legacy_publish', :as => nil
  get '/add/delete/:id/:security_id'  => 'post#legacy_delete',  :as => nil
  get '/add/delete/:id'               => 'post#legacy_delete',  :as => nil

  # Search
  get '/search/cat/:cat'     => 'search#index', :as => :search_by_cat
  get '/search/sub/:sub'     => 'search#index', :as => :search_by_sub
  get '/search'              => 'search#index', :as => :search

  # Legacy
  # TODO: Remove this on 2016-10-01
  get '/search/index(/:cat)' => 'search#index', :as => nil

  # Job
  get '/job'             => 'job#index',       :as => :job
  get '/subscriber'      => 'job#subscriber',  :as => :subscriber
  get '/unsubscribe'     => 'job#unsubscribe', :as => :unsubscribe
  get '/success'         => 'job#success',     :as => nil

  # Legacy
  # TODO: Remove this on 2016-10-01
  get '/job/index'       => 'job#index',       :as => nil
  get '/job/subscriber'  => 'job#subscriber',  :as => nil
  get '/job/unsubscribe' => 'job#unsubscribe', :as => nil

  # Redirect unknown to to home page
  # match '*path' => redirect('/')
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  caches_page :index
    
  def index
    @google_ad_manager = true
    @posts             = Post.recent_posts
    @photo_posts       = Post.recent_photo_posts
    @job_posts         = Post.recent_job_posts
    @time_ago          = Post.category_activity_metrics
  end

  def help
  end

  def about
  end

  def contact
  end

  def privacy
  end

  def terms
  end

  def safety
    redirect_to(safety_link) and return
  end

  def state
    no_cache_now
    render :text => 'OK!', :status => 200
  end

  def robots
    render :file => File.join(Rails.root, 'config', 'robots.txt'), :layout => false, :content_type => "text/plain"
  end

  private

  def safety_link
    "http://www.craigslist.org/about/scams"
  end
end

app/views/site/_categories.html.erb
<% categories.each do |category| %>
  <table class="<%= category.code %> category">
    <tr>
      <td class="category_header" colspan="<%= [category.columns.size, 1].max %>">
        <div class="category-header-title <%= category.icon %>">
          <%= link_to category.name, search_by_cat_path(category.id) %>
        </div>

        <% if @time_ago[category.id].present? %>
          <span class="category-header-timeAgo">
            (<%= time_ago_in_words @time_ago[category.id] %>)
          </span>
        <% end %>
      </td>
    </tr>

    <% if category.columns.present? %>
      <tr>
        <% category.columns.each_with_index do |subcategories, idx| %>
          <td class="categoryColumn cat-col-<%= idx %>">
            <ul>
              <% subcategories.each do |(id, name, is_cat)| %>
                <% if is_cat %>
                  <li><%= link_to name, search_by_cat_path(id) %></li>
                <% else %>
                  <li><%= link_to name, search_by_sub_path(id) %></li>
                <% end %>
              <% end %>
            </ul>
          </td>
        <% end %>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/site/_google_ad.html.erb
<!-- Google Ad Manager 2 -->
<!-- SUpost_Homepage_CompanyLogo_Top_300x100 -->
<!--
<div id='div-gpt-ad-1376573672379-1' style='width:300px; height:100px;'>
  <script type='text/javascript'>
    googletag.cmd.push(function() { googletag.display('div-gpt-ad-1376573672379-1'); });
  </script>
</div>
-->

<!-- SUpost_Homepage_BannerHigh_Top_300x250 -->
<div id="div-gpt-ad-1376573672379-0" style="width:300px; height:250px;">
  <script type="text/javascript">
    googletag.cmd.push(function() { googletag.display('div-gpt-ad-1376573672379-0'); });
  </script>
</div>

<br />

<!-- Big Header ad -->
<div class="bigHeaderAd">
  <!-- Google Ad Manager -->
  <!-- ca-pub-5913108846433714/supost_home_300x250 -->
  <script type="text/javascript">
    GA_googleFillSlot('supost_home_300x250');
  </script>
  <!-- Google Ad Manager -->
</div>

app/views/site/_overview.html.erb
<table id="classifiedsOverview" class="category">
  <tr>
    <td>
      <div class="classifiedOverviewHeader">
        <%= link_to 'overview', search_path %>
      </div>

      <% Category.active_categories.each do |category| %>
        <div class="classifiedsOverviewRow">
          <div class="classifiedsOverviewTitle <%= category.icon %>">
            <%= link_to category.display_name, search_by_cat_path(category.id) %>
          </div>

          <% if @time_ago[category.id].present? %>
            <div class="timeAgoShort"><%= short_time_ago @time_ago[category.id] %></div>
          <% end %>
        </div>
      <% end %>
    </td>
  </tr>
</table>

app/views/site/about.html.erb
<div class="about">
  <div class="infobox">
    <div class="infobox-header">about SUpost</div>

    <div class="paragraph">
      <%= image_tag "site/Greg.jpg", :class => "infobox-greg" %>

      <div>
        Welcome to SUpost. I built SUpost to enable Stanford students and staff to buy and sell their stuff. SUpost requires an @stanford.edu email in order to post. So, you can be sure that all items posted on SUpost are from people affiliated with Stanford. (The only exception to this email restriction is in the off-campus jobs section, in which anyone can post a job for a fee -- to help us cover the costs of operation.)
      </div>
		</div>
		
		<div class="paragraph">
      SUpost is the #1 marketplace at Stanford! SUpost gets over 1,000,000 page views per month from Stanford students, alumni, staff and faculty. Need to find housing? Check out the SUpost housing listings. Got something to sell? Post it! Looking to sublet your apartment? Post it! Need a bike for your ride to class through campus?  Post it! Post it! Tell everyone you know at Stanford to post one item they want to sell on SUpost, and watch this site continue to be an incredibly useful resource at Stanford. 
		</div>
			
    <div class="paragraph">Greg Wientjes <br/><br/><br/><br/> </div>
	</div>
    
	<div class="infobox management">
    <div class="infobox-header">SUpost management</div>
		
    <div class="infobox-contents">
      <div class="founder">Greg Wientjes</div>
      <div class="founder-title">Co-Founder</div>
      <div class="founder-description">Greg Wientjes received a PhD, MS and BS, all from Stanford University.</div>
    </div>
  </div>
</div>

app/views/site/contact.html.erb
<div class="infobox">
  <div class="infobox-header">contact us</div>

  <div class="sup-info-contact">
    <a href="mailto:contact@supost.com?subject=SUpost">contact@supost.com</a>
  </div>
</div>

app/views/site/help.html.erb
<div>
  <div class="sup-info">
    <table class="static-page">
      <tr>
        <td width="720" valign="top">
          <div class="sup-info-header">help</div>
          <p><strong>How to submit a post</strong></p>
          <p>All postings are free. Here's a quick outline of the process:</p>
          <ul>
            <li>go to the home page for SUpost</li>
            <li>click on the "post" link in the top right corner</li>
            <li>select the category in which you would like to post</li>
            <li>make the appropriate selections in the next few screens, until you get to the main post form</li>
            <li>fill in the blank fields as needed, and select "continue"</li>
            <li>review your post, back up and edit if necessary, then select "continue"</li>
            <li>review the Terms of Use on the next page, then click "ACCEPT the terms of use" if you agree</li>
            <li>review the information in the confirmation screen</li>
            <li>check your email for the self-publishing email message that should have been sent to you</li>
            <li>use the link in that email message to access the publishing form for your post</li>
            <li>make any last-minute changes, then click the "publish" button</li>
            <li>once you publish your post, it will appear on the site within 15 minutes</li>
            <li>keep the email that contains your self-publishing link, because you can use it later to edit or delete the post.</li>
            <li>if you lose or delete this email, you can have the edit/delete link resent</li>
          </ul>
          <p>&nbsp;</p>

          <p><strong>How to reply to a post</strong></p>
          <p>To reply to a post, type a message into the reply text box below the post.</p>
          <p>Your email will be received by the poster.</p>
          <p>If the poster has not provided a reply email address, look for an alternative method of contact at the bottom of the post under "Other ways to contact poster:"</p>
          <p>&nbsp;</p>

          <p><strong>How to include a picture</strong></p>
          <p>Currently you can add pictures to your post in the housing and for sale categories by selecting "Add images to this posting" at the bottom of the posting form.</p>
          <p>You will be given the option to include four images. By selecting "Browse" you can search through your computer's directory and select the file path to your picture. Selecting "continue with this posting" will bring you back to a review screen of what your posting will look like with the picture included. If everything looks ok, select "continue."</p>
          <p>For all other categories your picture must be uploaded on to a server (not on a disk or your hardrive). Once on a server you can either provide the URL (web address) for your picture for people to click on or use an an HTML image tag to have your post appear in the post.</p>
          <p>&nbsp;</p>
        </td>
      </tr>

      <tr>
        <td>
          <div class="sup-info-header">FAQ</div>
          <p><strong>Where is my post?</strong></p>
          <p>Free postings don't post automatically, you must publish them first.</p>

          <p>All classified postings take approximately 15 minutes from the time you publish the posting until it appears on the site.</p>

          <p>To see your posting, go to the category where you posted it, look under the date it was submitted and refresh/reload your browser.</p>

          <p>If you've correctly followed our posting directions, waited 30 minutes, refreshed your browser on the correct category index page, and your posting still is not there - then it may have been flagged and deleted by the SUpost community.</p>
          <p>You can check on the status of your posting by following the link provided in your self-publishing email.</p>

          <p>Please note that editing your post does not bring it up to the current date.</p>
          <p>&nbsp;</p>

          <p><strong>Where is my self-publishing email? </strong></p>
          <p>If you have successfully submitted your posting and still have not received the email to publish your post, here are some things to consider:</p>
          <ul>
            <li>Make sure you entered your email address correctly on the posting form - it only takes one typo!.</li>
            <li>Some email providers and ISPs have implemented "spam filters" which we have found are often badly designed or misconfigured - sometimes resulting in self-publishing &amp; other SUpost emails being intercepted.</li>
            <li>Network problems between ISPs can delay email transmission, sometimes for many hours - consider stretching out, getting some fresh air and checking back later.</li>
          </ul>

          <p><strong>Why was my posting deleted?</strong></p>
          <p>There are 4 possibile reasons:</p>
          <ul>
            <li>Your posting has expired.</li>
            <li>Your posting has been flagged off the site</li>
            <li>Your posting has been brought to the attention of SUpost, determined to be outside our Terms of Use, and removed by one of our staff.</li>
            <li>You deleted the posting yourself.</li>
          </ul>
        </td>
      </tr>

      <tr>
        <td>&nbsp;</td>
      </tr>

      <tr>
        <td class="center"><br /></td>
      </tr>
    </table>
  </div>
</div>

app/views/site/index.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag 'stripe.css' %>
<% end %>

<table>
  <tr id="mainContent">
    <td id="leftNavBar">
      <div id="postToDiv">
        <%= link_to "post to classifieds", new_post_path %>
        <div class="at_stanford_required">@stanford.edu required</div>
      </div>

      <div class="buy_job_post">
        <%= link_to 'buy job post', buy_job_post_link %>
      </div>

      <table id="classifieds">
        <tr>
          <td>
            <%= render :partial => 'overview' %>

            <%= render :partial => 'categories', :locals => { :categories => Category.first_active_categories } %>

            <div class="buy_job_post_lower">
              <%= link_to 'buy job post', buy_job_post_link %>
            </div>

            <%= render :partial => 'categories', :locals => { :categories => Category.second_active_categories } %>

            <div class="appStoreDownload">
              <%= link_to image_tag('site/AppStore.png', :alt => 'Download on AppStore'), sum_app_link, :target => '_blank' %>
            </div>
          </td>
        </tr>
      </table>
    </td>

    <td id="indexBody">
      <table id="indexBodyContent">
        <tr>
          <td colspan="2" id="tickerTd">
            <div class="post_photos clearfix">
              <% @photo_posts.each_with_index do |post, idx| %>
                <div class="post_photo" title="<%= post.name %>">
                  <%= link_to post_photo_tag(post.ticker_photo, :class => 'photo_image_tag', :alt => "Ticker #{idx}"), post_path(post.id) %>

                  <div class="post_photo_title">
                    <%= link_to post.truncated_name(21), post_path(post.id) %>
                  </div>

                  <%= post_time_tag(post) %>
                </div>
              <% end %>
            </div>
          </td>
        </tr>

        <tr>
          <td id="recentPosts">
            <div class="moduleTitle">
              <%= link_to 'recently posted', search_path %>
            </div>

            <% @posts.each do |post| %>
              <div class="one-result">
                <%= post_title_tag post %>
                <%= post_time_tag post %>
                <%= stripe_checkout_link(post) %>
              </div>
            <% end %>
          </td>

          <td id="thoughts">
            <% if @job_posts.present? %>
              <div class="moduleTitle">
                <%= link_to 'featured job posts', search_by_cat_path(Category::OFF_CAMPUS_JOBS) %>
              </div>

              <div class="job-posts-container">
                <% @job_posts.each do |post| %>
                  <div class="one-result">
                    <%= post_title_tag post %>
                  </div>
                <% end %>
              </div>
            <% end %>

            <div class="homepage-right-column-info">
              <%= link_to 'Safety: Never wire transfer money and avoid fake checks.', safety_link, :target => '_blank' %>
              <div class="notSponsored">SUpost is not sponsored by, endorsed by, or affiliated with Stanford University.</div>
            </div>

            <%= render :partial => 'google_ad' %>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>

app/views/site/privacy.html.erb
<div class="sup-info">
  <div class="sup-info-header">privacy policy</div>

  <p>SUpost has established this privacy policy to explain to you how your information is protected, collected and used, which may be updated by SUpost from time to time. SUpost will provide notice of materially significant changes to this privacy policy by posting notice on the SUpost site.</p>
  <p></p>

  <h4>1. Protecting your privacy</h4>
  <ul>
    <li>We don't run banner ads, pop ups, pop unders, or any other kind of commercial ads.</li>
    <li>We don't share your information with third parties for marketing purposes.</li>
    <li>We don't engage in cross-marketing or link-referral programs with other sites.</li>
    <li>We don't employ tracking devices for marketing purposes ("cookies", "web beacons", single-pixel gifs).</li>
    <li>We don't send you unsolicited communications for marketing purposes.</li>
    <li>We offer email anonymization &amp; relay, to reduce 3rd party harvesting &amp; spam.</li>
    <li>Account information is password-protected. Keep your password safe.</li>
    <li>SUpost does not knowingly collect any information from persons under the age of 13. If SUpost learns that a posting is by a person under the age of 13, SUpost will remove that post.</li>
    <li>SUpost, or people who post on SUpost, may provide links to third party websites, which may have different privacy practices. We are not responsible for, nor have any control over, the privacy policies of those third party websites, and encourage all users to read the privacy policies of each and every website visited.</li>
  </ul>

  <h4>2. Data we collect</h4>
  <ul>
    <li>We sometimes collect your email address, for purposes such as sending self-publishing and confirmation emails, authenticating user accounts, providing subscription email services, registering for forums, etc.</li>
    <li>For job postings, we collect contact information, such as name(s), phone/fax number(s), and address for billing purposes.</li>
    <li>SUpost does not store credit card information.</li>
    <li>We may collect personal information if you provide it in feedback or comments, post it on our classifieds or interactive forums, or if you contact us directly. Please do not post any personal information on SUpost's forums or classifieds that you expect to keep private.</li>
    <li>Our web logs collect standard web log entries for each page served, including your IP address, page URL, and timestamp. Web logs help us to diagnose problems with our server, to administer the SUpost site, and to otherwise provide our service to you.</li>
  </ul>

  <h4>3. Data we store</h4>
  <ul>
    <li>All classified and forum postings are stored in our database, even after "deletion," and may be archived elsewhere.</li>
    <li>Our web logs and other records are stored indefinitely.</li>
    <li>Although we make good faith efforts to store the information in a secure operating environment that is not available to the public, we cannot guarantee complete security.</li>
  </ul>

  <h4>4. Circumstances in which SUpost may release information</h4>
  <ul>
    <li>SUpost may disclose information about its users if required to do so by law or in the good faith belief that such disclosure is reasonably necessary to respond to subpoenas, court orders, or other legal process.</li>
    <li>SUpost may also disclose information about its users to law enforcement officers or others, in the good faith belief that such disclosure is reasonably necessary to: enforce our <%= link_to 'Terms of Use', terms_path %>; respond to claims that any posting or other content violates the rights of third-parties; or protect the rights, property, or personal safety of SUpost, its users or the general public.</li>
  </ul>

  <h4>5. Feedback</h4>
  We welcome your feedback on this document.
</div>

app/views/site/terms.html.erb
<div>
  <div class="sup-info">
    <div class="sup-info-header">terms of use</div>
    <%= render :partial => 'terms' -%>
  </div>
</div>