config/routes.rb
Supost::Application.routes.draw do
  root :to => 'site#index'

  # Admin
  namespace :admin do
    root :to => 'posts#index'

    resources :events, :only => [:index]

    resources :payments, :only => [:index]

    resources :spammers, :only => [:index, :create, :destroy] do
      member do
        get :posts
      end
    end

    resources :scammers, :only => [:index, :create, :destroy] do
      member do
        get :messages
      end
      collection do
        get :find
      end
    end

    resources :messages, :only => [:index] do
      member do
        get  :similar
        get  :report
        post :report
      end
    end

    get 'profile'  => 'users#profile',  :as => :profile
    put 'profile'  => 'users#profile',  :as => :profile

    get 'password' => 'users#password', :as => :password
    put 'password' => 'users#password', :as => :password

    resources :users do
      member do
        post :reset
      end
    end

    resources :posts do
      member do
        get  :readonly
        post :publish
        post :release
        post :notify
        get  :similar
        get  :report
        post :report
      end
      collection do
        get :job
      end
      resources :messages, :only => :index
    end

    get  'login'  => 'sessions#new',     :as => :login
    post 'login'  => 'sessions#create',  :as => :login
    get  'logout' => 'sessions#destroy', :as => :logout
  end

  mount DelayedJobWeb => '/delayed_job'

  # Stripe
  post '/webhook'         => 'stripe#webhook'
  post '/charge/:post_id' => 'stripe#charge', :as => :charge

  # Site
  get '/about'        => 'site#about',   :as => :about
  get '/contact'      => 'site#contact', :as => :contact
  get '/privacy'      => 'site#privacy', :as => :privacy
  get '/terms'        => 'site#terms',   :as => :terms
  get '/help'         => 'site#help',    :as => :help
  get '/safety'       => 'site#safety',  :as => :safety
  get '/status'       => 'site#state',   :as => :status
  get '/robots.txt'   => 'site#robots',  :as => nil

  # Legacy
  # TODO: Remove this on 2016-10-01
  get '/site(/index)' => 'site#index',   :as => nil
  get '/site/about'   => 'site#about',   :as => nil
  get '/site/contact' => 'site#contact', :as => nil
  get '/site/privacy' => 'site#privacy', :as => nil
  get '/site/terms'   => 'site#terms',   :as => nil
  get '/site/help'    => 'site#help',    :as => nil

  # Add
  get  '/add'                          => 'add#index',   :as => :new_post
  get  '/add/cat/:cat(/sub/:sub)'      => 'add#index',   :as => :add_post
  post '/add/cat/:cat(/sub/:sub)'      => 'add#index',   :as => :add_post
  get  '/add/preview/:id'              => 'add#preview', :as => :preview_post
  post '/add/confirm/:id'              => 'add#confirm', :as => :confirm_post
  get  '/add/success'                  => 'add#success', :as => :success

  # Legacy
  # TODO: Remove this on 2016-10-01
  get  '/add/index(/:cat)' => 'add#index', :as => nil
  post '/add/index/:cat'   => 'add#index', :as => nil

  # Post
  get  '/post/index/:id'             => 'post#index',   :as => :post
  post '/post/index/:id'             => 'post#index',   :as => :post
  get  '/post/publish/:access_token' => 'post#publish', :as => :publish_post
  get  '/post/delete/:access_token'  => 'post#delete',  :as => :delete_post

  # Legacy
  # TODO: Remove this on 2016-10-01
  get '/add/publish/:id/:security_id' => 'post#legacy_publish', :as => nil
  get '/add/publish/:id'              => 'post#legacy_publish', :as => nil
  get '/add/delete/:id/:security_id'  => 'post#legacy_delete',  :as => nil
  get '/add/delete/:id'               => 'post#legacy_delete',  :as => nil

  # Search
  get '/search/cat/:cat'     => 'search#index', :as => :search_by_cat
  get '/search/sub/:sub'     => 'search#index', :as => :search_by_sub
  get '/search'              => 'search#index', :as => :search

  # Legacy
  # TODO: Remove this on 2016-10-01
  get '/search/index(/:cat)' => 'search#index', :as => nil

  # Job
  get '/job'             => 'job#index',       :as => :job
  get '/subscriber'      => 'job#subscriber',  :as => :subscriber
  get '/unsubscribe'     => 'job#unsubscribe', :as => :unsubscribe
  get '/success'         => 'job#success',     :as => nil

  # Legacy
  # TODO: Remove this on 2016-10-01
  get '/job/index'       => 'job#index',       :as => nil
  get '/job/subscriber'  => 'job#subscriber',  :as => nil
  get '/job/unsubscribe' => 'job#unsubscribe', :as => nil

  # Redirect unknown to to home page
  # match '*path' => redirect('/')
end

app/models/user.rb
require 'securerandom'

class User < ActiveRecord::Base
  EMAIL_REGEX = /^[A-Z0-9._%-]+@([A-Z0-9-]+\.)+[A-Z]{2,4}$/i

  before_validation :remove_whitespaces!
  before_save :encrypt_password

  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation, :disabled
  attr_accessor   :password

  validates_presence_of     :first_name
  validates_length_of       :first_name, :maximum => 255, :allow_nil => true, :allow_blank => true

  validates_presence_of     :last_name
  validates_length_of       :last_name, :maximum => 255, :allow_nil => true, :allow_blank => true

  validates_presence_of     :email
  validates_format_of       :email, :with => EMAIL_REGEX, :allow_nil => true, :allow_blank => true
  validates_length_of       :email, :maximum => 255, :allow_nil => true, :allow_blank => true
  validates_uniqueness_of   :email, :allow_nil => true, :allow_blank => true

  validates_presence_of     :password, :on => :create
  validates_length_of       :password, :in => 6..32, :allow_nil => true, :allow_blank => true
  validates_confirmation_of :password, :allow_nil => true, :allow_blank => true

  scope :active, :conditions => { :disabled => false }

  def reset_password!
    password = SecureRandom.hex(6)
    self.update_attributes!(:password => password, :password_confirmation => password)
    password
  end

  def can_update?(user)
    if self.new_record? || user.blank? || user.new_record?
      false
    elsif user.admin?
      false
    elsif self.id == user.id
      false
    elsif self.admin?
      true
    else
      false
    end
  end

  def admin?
    user_type == 'Admin'
  end

  def enabled?
    !disabled?
  end

  def name
    "#{first_name} #{last_name}".strip
  end

  def created_on
    created_at.strftime('%b %d, %Y')
  end

  def change_password(current, password_params)
    if new_record?
      errors.add :base, 'Cannot change password for new record'
      false
    elsif authenticate!(current)
      self.update_attributes password_params.slice(:password, :password_confirmation)
    else
      errors.add :base, 'Current password is invalid'
      false
    end
  end

  def authenticate!(password)
    self.password_hash == BCrypt::Engine.hash_secret(password, self.password_salt)
  end

  def self.authenticate(email, password)
    user = active.find_by_email(email)
    if user && user.authenticate!(password)
      user
    else
      nil
    end
  end

  private

  def remove_whitespaces!
    self.first_name = self.first_name.strip if self.first_name.respond_to?(:strip)
    self.last_name = self.last_name.strip if self.last_name.respond_to?(:strip)
    self.email = self.email.strip if self.email.respond_to?(:strip)
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(self.password, self.password_salt)
    end
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  before_filter :admin_required,    :except => [:profile, :password]
  before_filter :find_user,         :only   => [:show, :edit, :update, :destroy, :reset]
  before_filter :find_current_user, :only   => [:profile, :password]

  def index
    @users = User.page(params[:page]).per(10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      redirect_to admin_users_url, :notice => 'New user was created successfully!'
    else
      render :action => 'new'
    end
  end

  def show
    render :action => 'edit'
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to admin_users_url, :notice => 'User was updated successfully!'
    else
      render :action => 'edit'
    end
  end

  def destroy
    notice = "User was #{@user.enabled? ? 'disabled' : 'enabled'} successfully!"
    @user.toggle!(:disabled)
    redirect_to admin_users_url, :notice => notice
  end

  def reset
    password = @user.reset_password!
    notice = "New password for <b>#{@user.email}</b> is <b>#{password}</b>.".html_safe
    redirect_to admin_users_url, :notice => notice
  end

  def profile
    if request.put? && @user.update_attributes(profile_params)
      redirect_to admin_profile_url, :notice => 'Your profile was updated successfully!'
    else
      render
    end
  end

  def password
    if request.put? && @user.change_password(params[:password], password_params)
      redirect_to admin_password_url, :notice => 'Your password was changed successfully!'
    else
      render
    end
  end

  private

  def admin_required
    redirect_to admin_root_url and return unless current_user && current_user.admin?
  end

  def find_user
    @user = User.find params[:id]
    redirect_to admin_users_url and return unless current_user.can_update?(@user)
  end

  def find_current_user
    @user = User.find current_user.id
  end

  def user_params
    params[:user].slice(:first_name, :last_name, :email, :password, :password_confirmation, :disabled)
  end

  def profile_params
    params[:user].slice(:first_name, :last_name, :email)
  end

  def password_params
    params[:user].slice(:password, :password_confirmation)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
  def edit_user_link(user)
    if current_user.can_update?(user)
      link_to user.name, edit_admin_user_path(user)
    else
      content_tag :span, user.name
    end
  end

  def reset_password_link(user)
    return unless current_user.can_update?(user)

    options = {
      :title   => 'Reset password for this user',
      :confirm => "Are you sure you want to reset password for #{user.email}?",
      :method  => :post
    }

    link_to image_tag('admin/reset.png'), reset_admin_user_path(user), options
  end

  def enable_user_link(user)
    return unless current_user.can_update?(user)

    action = user.enabled? ? 'Disable' : 'Enable'

    options = {
      :title   => "#{action} this user",
      :method  => :delete
    }

    path = if user.enabled?
             'admin/disable.png'
           else
             'admin/enable.png'
           end

    link_to image_tag(path), admin_user_path(user), options
  end
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <%= render :partial => '/shared/errors', :locals => { :record => @user } %>

  <table class='user-form'>
    <colgroup>
      <col class='label'>
      <col class='value'>
    </colgroup>

    <tr>
      <td><%= f.label :first_name %></td>
      <td><%= f.text_field :first_name, :maxlength => 255 %></td>
    </tr>

    <tr>
      <td><%= f.label :last_name %></td>
      <td><%= f.text_field :last_name, :maxlength => 255 %></td>
    </tr>

    <tr>
      <td><%= f.label :email %></td>
      <td><%= f.text_field :email, :maxlength => 255 %></td>
    </tr>

    <tr>
      <td><%= f.label :password %></td>
      <td><%= f.password_field :password, :maxlength => 255 %></td>
    </tr>

    <tr>
      <td><%= f.label :password_confirmation, 'Confirmation' %></td>
      <td><%= f.password_field :password_confirmation, :maxlength => 255 %></td>
    </tr>

    <tr>
      <td><%= f.label :disabled %></td>
      <td><%= f.check_box :disabled %></td>
    </tr>

    <tr>
      <td>&nbsp;</td>
      <td>
        <% button_text = @user.new_record? ? 'Create' : 'Update' %>
        <%= f.submit button_text, :disable_with => button_text %>
        &nbsp;&nbsp;
        <%= link_to 'Cancel', admin_users_path %>
      </td>
    </tr>
  </table>
<% end %>

app/views/admin/users/edit.html.erb
<div id="inner-main">
  <h1>Edit User</h1>
  <%= render :partial => 'form' %>
</div>

app/views/admin/users/index.html.erb
<h1>Users</h1>

<%= render :partial => '/shared/notice' %>

<table class="data users">
  <colgroup>
    <col class="id" />
    <col class="name" />
    <col class="email" />
    <col class="type" />
    <col class="status" />
    <col class="created-on" />
    <col class="action" />
    <col class="action" />
  </colgroup>

  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Email</th>
    <th>Type</th>
    <th>Status</th>
    <th>Created On</th>
    <th></th>
    <th></th>
  </tr>

  <% @users.each_with_index do |u, index| %>
    <% can_update_user = current_user.can_update?(u) %>
    <tr class="row-<%= index % 2 %>">
      <td class="right"><%= u.id %></td>
      <td><%= edit_user_link(u) %></td>
      <td><%= u.email %></td>
      <td class="center"><%= u.user_type %></td>
      <td class="center"><%= u.disabled? ? 'Disabled' : 'Enabled' %></td>
      <td class="center"><%= u.created_on %></td>
      <td class="center"><%= reset_password_link(u) %></td>
      <td class="center"><%= enable_user_link(u) %></td>
    </tr>
  <% end %>
</table>

<%= render :partial => '/shared/pagination', :locals => { :records => @users } %>

app/views/admin/users/new.html.erb
<div id="inner-main">
  <h1>New User</h1>
  <%= render :partial => 'form' %>
</div>

app/views/admin/users/password.html.erb
<div id="inner-main">
  <h1>Change Password</h1>

  <%= form_for [:admin, @user], :url => admin_password_path, :html => { :autocomplete => 'off' } do |f| %>
    <%= render :partial => '/shared/notice' %>
    <%= render :partial => '/shared/errors', :locals => { :record => @user } %>

    <table class='user-form'>
      <colgroup>
        <col class='label'>
        <col class='value'>
      </colgroup>

      <tr>
        <td><%= label_tag :password, 'Current password' %></td>
        <td><%= password_field_tag :password, params[:password], :maxlength => 255 %></td>
      </tr>

      <tr>
        <td><%= f.label :password, 'New password' %></td>
        <td><%= f.password_field :password, :maxlength => 255 %></td>
      </tr>

      <tr>
        <td><%= f.label :password_confirmation, 'Confirmation' %></td>
        <td><%= f.password_field :password_confirmation, :maxlength => 255 %></td>
      </tr>

      <tr>
        <td>&nbsp;</td>
        <td>
          <%= f.submit 'Change', :disable_with => 'Change' %>
          &nbsp;&nbsp;
          <%= link_to 'Profile', admin_profile_path %>
          &nbsp;&nbsp;
          <%= link_to 'Cancel', admin_root_path %>
        </td>
      </tr>
    </table>
  <% end %>
</div>

app/views/admin/users/profile.html.erb
<div id="inner-main">
  <h1>Profile</h1>

  <%= form_for [:admin, @user], :url => admin_profile_path do |f| %>
    <%= render :partial => '/shared/notice' %>
    <%= render :partial => '/shared/errors', :locals => { :record => @user } %>

    <table class='user-form'>
      <colgroup>
        <col class='label'>
        <col class='value'>
      </colgroup>

      <tr>
        <td><%= f.label :first_name %></td>
        <td><%= f.text_field :first_name, :maxlength => 254 %></td>
      </tr>

      <tr>
        <td><%= f.label :last_name %></td>
        <td><%= f.text_field :last_name, :maxlength => 254 %></td>
      </tr>

      <tr>
        <td><%= f.label :email %></td>
        <td><%= f.text_field :email, :maxlength => 254 %></td>
      </tr>

      <tr>
        <td>&nbsp;</td>
        <td>
          <%= f.submit 'Update', :disable_with => 'Update' %>
          &nbsp;&nbsp;
          <%= link_to 'Change Password', admin_password_path %>
          &nbsp;&nbsp;
          <%= link_to 'Cancel', admin_root_path %>
        </td>
      </tr>
    </table>
  <% end %>
</div>